version: "3"
services:
  haproxy:
    container_name: camel-load-balance
    image: dockercloud/haproxy:1.6.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${HAPROXY_HOST}:80
    links:
      - frontend
  camel-database:
    container_name: camel-database
    image: mongo
    ports:
      - "${MONGODB_HOST}:27017"
  backend:
    image: camel-backend:${CAMEL_VERSION}
    volumes:
      - ${CAMEL_SAVE_DIR}:/tmp/camel
    ports:
      - "${CAMEL_BACKEND_HOST_PORT}:3000"
  frontend:
    image: camel-frontend:${CAMEL_VERSION}
