version: "3"
services:
  camel-backend:
    container_name: camel-backend
    restart: always
    build: https://github.com/Rayleigh3105/camel24-backend.git
    ports:
      - "8181:80"
    volumes:
      - .:/app
    links:
      - mongo
  camel-frontend:
    container_name: camel-frontend
    hostname: localhost
    restart: always
    build: https://github.com/Rayleigh3105/camel24-angular.git
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
