version: "3"
services:
  camel-backend:
    container_name: camel-backend
    restart: always
    image: mvogt3105/camel-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - C:\\Users\\morit\\camel:\\root\\camel
    links:
      - mongo
  camel-frontend:
    container_name: camel-frontend
    restart: always
    image: mvogt3105/camel-frontend:latest
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
