#%RAML 1.0
---
title: Camel-24 Online Auftrag Service
baseUri: http://localhost:3000
version: 0.0

/user:
  post:
    description: Erstellt einen Benutzer.
    responses:
      201:
        body:
          application/json:
            example: !include json/user/post/responsePostUser.json

/user/login:
   post:
     description: Es wird ein Token bei erfolreicher Anmeldung generiert.
     responses:
       200:
         body:
           application/json:
             example: !include json/user/post/responsePostUser.json

